
### Get All Products
GET http://localhost:3000/products

### Create a Product
POST http://localhost:3000/products
Content-Type: application/json

{ 
    "name": "iPhone 15",
    "price": "1099"
}



### Get Product by Id
GET http://localhost:3000/products/653f8f32bd09a34ee4078cba


### Update Product by Id
PATCH  http://localhost:3000/products/653f8f32bd09a34ee4078cb
Content-Type: application/json

{
    "price": 1149
}


### Delete Product by Id
DELETE  http://localhost:3000/products/653f8ce1f16f1ddb39bd694

#### Error Handling 404 not found 
GET http://localhost:3000/abc_xyz


###
GET http://localhost:3000/test?name=iMac&price=2399

###
GET http://localhost:3000/test/1234567/iMac

###
POST http://localhost:3000/test
Content-Type: application/json

{
    "name": "iMacPro",
    "price": 4999
}


###
POST http://localhost:3000/test
Content-Type: application/x-www-form-urlencoded

name=iMac&price=4999