
### Get All Products
GET http://localhost:3000/products

### Create a Product
POST http://localhost:3000/products
Content-Type: application/json

{ 
    "name": "iPhone 15",
    "price": "1099"
}



### Get Product by Id
GET http://localhost:3000/products/653f8f32bd09a34ee4078cba


### Update Product by Id
PATCH  http://localhost:3000/products/653f8f32bd09a34ee4078cba
Content-Type: application/json

{
    "name": "iPhone 11 Pro Max Gold"
}
### Delete Product by Id
DELETE  http://localhost:3000/products/653f8c7df16f1ddb39bd6941

#### Error Handling
GET http://localhost:3000/

###
GET http://localhost:3000/test?name=iMac&price=2399

###
GET http://localhost:3000/test/1234567/iMac

###
POST http://localhost:3000/test
Content-Type: application/json

{
    "name": "iMacPro",
    "price": 4999
}


###
POST http://localhost:3000/test
Content-Type: application/x-www-form-urlencoded

name=iMac&price=4999